// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atoumfieydjuxsgapwfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0b3VtZmlleWRqdXhzZ2Fwd2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQxMDAsImV4cCI6MjA2NTQ5MDEwMH0.CBYF8sDJNddUOX285nYXoBs6Tx1RTGMITFbrKQ1elbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);